networks:
  main:

services:
  webserver:
    build: docker/nginx
    container_name: qa-webserver
    working_dir: /application
    restart: unless-stopped
    volumes:
      - .:/application
      - ./docker/nginx/nginx-vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    networks:
      - main
